seed: 42
dropout: 0.1
lr: 1e-4
weight_decay: 1e-4
batch_size: 64
epochs: 3000
early_stopping: True
input_dropout: 0.1
n_splits: 5
random_state: 42
loss_fn: "default"  # "default" or "bce"
pathway: null  # set to a pathway name to run a single target
run_all_pathways: True

