seed: 42
dropout: 0.3
lr: 0.00005
weight_decay: 0.01
batch_size: 64
epochs: 3000
early_stopping: True
input_dropout: 0.3
n_splits: 5
random_state: 42
loss_fn: "mse"  # "mse", "l1", or "huber"
trait: "nk_cells"
score_type: "PLL"
normalize: False  # Apply z-score normalization to inputs and targets
